export const USERS_DI_CONSTANTS = {
  USERS_REPOSITORY: Symbol('USERS_REPOSITORY'),
  USERS_SERVICE: Symbol('USERS_SERVICE'),
  USERS_TOKENS_SERVICE: Symbol('USERS_TOKENS_SERVICE'),
  CREATE_USER_CASE: Symbol('CREATE_USER_CASE'),
  LOGIN_CASE: Symbol('LOGIN_CASE'),
  REFRESH_TOKENS_CASE: Symbol('REFRESH_TOKENS_CASE'),
};
