export const API_COMMON_DI_CONSTANTS = {
  LOGGER: Symbol('LOGGER'),
  ERROR_FILTER: Symbol('ERROR_FILTER'),
  AUTH_GUARD: Symbol('AUTH_GUARD'),
  REQUEST_ID_HEADER_INTERCEPTOR: Symbol('REQUEST_ID_HEADER_INTERCEPTOR'),
};
